export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCH_DATA_FINISH = "FETCH_DATA_FINISH";

export const POST_DATA_START = "POST_DATA_START";
export const POST_DATA_REQUEST = "POST_DATA_REQUEST";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_ERROR = "POST_DATA_ERROR";
export const POST_DATA_FINISH = "POST_DATA_FINISH";
